name: Publish

on:
  push:
    branches:
      - dev

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    #if: ${{ github.repository_owner == 'electron-react-boilerplate' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Git Sumbodule Update
        run: git submodule update --init --recursive

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm install
      - name: Set Beta Build
        run: |
          sed -i "s|main|dev|g" "./src/data/branch.json"
          sed -i "s|emudeck-electron|emudeck-electron-dev|g" "./package.json"
          sed -i "s|version\": \"|version\": \"dev-|g" "./package.json"

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          #APPLE_ID: ${{ secrets.APPLE_ID }}
          #APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          #CSC_LINK: ${{ secrets.CSC_LINK }}
          #CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          #npm run build:${GITHUB_REF##*/} -> Branch name
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always --linux
